
import Model from '@/components/Model'
import './globals.css'

export const metadata = {
  title: 'Drag And Drop (Todo)',
  description: 'Generated by DigiSprint',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
      <Model/>
      </body>
    </html>
  )
}
